// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Invoice struct {
	ID       string  `json:"id"`
	Customer string  `json:"customer"`
	Amount   float64 `json:"amount"`
	Status   string  `json:"status"`
}

type Mutation struct {
}

type Query struct {
}
