package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"solid_go/db/graphql/graph/model"
)

// CreateInvoice is the resolver for the createInvoice mutation.
// Mutations modify server-side state — here it appends to the in-memory invoices slice.
// In production this would persist to a database and return the persisted record.
func (r *mutationResolver) CreateInvoice(ctx context.Context, customer string, amount float64, status string) (*model.Invoice, error) {
	inv := &model.Invoice{
		ID:       fmt.Sprintf("%d", len(r.invoices)+1), // auto-increment ID from slice length
		Customer: customer,
		Amount:   amount,
		Status:   status,
	}
	r.invoices = append(r.invoices, inv) // mutable state on the Resolver struct
	return inv, nil
}

// Invoices is the resolver for the invoices query — returns the full list.
// Queries must be side-effect free (read-only).
func (r *queryResolver) Invoices(ctx context.Context) ([]*model.Invoice, error) {
	return r.invoices, nil
}

// Invoice is the resolver for the invoice query — looks up a single invoice by ID.
// Returns nil (not an error) when the ID is not found; GraphQL represents this as a null field.
func (r *queryResolver) Invoice(ctx context.Context, id string) (*model.Invoice, error) {
	for _, inv := range r.invoices {
		if inv.ID == id {
			return inv, nil
		}
	}
	return nil, nil // GraphQL null response — not a server error
}

// Mutation returns the MutationResolver, which is this file's mutationResolver type.
// gqlgen generates these wiring methods; do not edit them manually.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns the QueryResolver.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// mutationResolver and queryResolver embed *Resolver to share its state (invoices slice).
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
