// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: proto/invoice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      string                 `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_proto_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_proto_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *Invoice) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type InvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceResponse) Reset() {
	*x = InvoiceResponse{}
	mi := &file_proto_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceResponse) ProtoMessage() {}

func (x *InvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceResponse.ProtoReflect.Descriptor instead.
func (*InvoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_invoice_proto protoreflect.FileDescriptor

const file_proto_invoice_proto_rawDesc = "" +
	"\n" +
	"\x13proto/invoice.proto\x12\ainvoice\"=\n" +
	"\aInvoice\x12\x1a\n" +
	"\bcustomer\x18\x01 \x01(\tR\bcustomer\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"+\n" +
	"\x0fInvoiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2M\n" +
	"\x0eInvoiceService\x12;\n" +
	"\rCreateInvoice\x12\x10.invoice.Invoice\x1a\x18.invoice.InvoiceResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_invoice_proto_rawDescOnce sync.Once
	file_proto_invoice_proto_rawDescData []byte
)

func file_proto_invoice_proto_rawDescGZIP() []byte {
	file_proto_invoice_proto_rawDescOnce.Do(func() {
		file_proto_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_invoice_proto_rawDesc), len(file_proto_invoice_proto_rawDesc)))
	})
	return file_proto_invoice_proto_rawDescData
}

var file_proto_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_invoice_proto_goTypes = []any{
	(*Invoice)(nil),         // 0: invoice.Invoice
	(*InvoiceResponse)(nil), // 1: invoice.InvoiceResponse
}
var file_proto_invoice_proto_depIdxs = []int32{
	0, // 0: invoice.InvoiceService.CreateInvoice:input_type -> invoice.Invoice
	1, // 1: invoice.InvoiceService.CreateInvoice:output_type -> invoice.InvoiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_invoice_proto_init() }
func file_proto_invoice_proto_init() {
	if File_proto_invoice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_invoice_proto_rawDesc), len(file_proto_invoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_invoice_proto_goTypes,
		DependencyIndexes: file_proto_invoice_proto_depIdxs,
		MessageInfos:      file_proto_invoice_proto_msgTypes,
	}.Build()
	File_proto_invoice_proto = out.File
	file_proto_invoice_proto_goTypes = nil
	file_proto_invoice_proto_depIdxs = nil
}
